### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by glowkeeper** [glowkeeper/mccs-alpha-api-ui#1]
+ How should it look - some initial thoughts on the layout would be good?

**Comment by dilgreen** [comment]
I am thinking that it will be interesting to take this as a 'mobile first', rather than a 'responsive' piece of work - as we have already done responsive on the OCN site.
I made this image in marvelapp - which, if you don't know it, is a UI prototyping tool.https://marvelapp.com/8b1gg69. I'm on the free plan, so could easily use something else.
 It was made for the Capacity clubs/Mutual Credit clubs audience, but easily tweaked. 
![CapClubMobileScreen](https://user-images.githubusercontent.com/5934679/81471461-2e650000-91e9-11ea-875e-d17a62668889.png)

**Comment by glowkeeper** [comment]
@dilgreen - wow - thanks! But I'm going to park that for future reference - at this early stage, I was hoping for some hints on the homepage and login screens :)

**Comment by dilgreen** [comment]
I know - I need to look at the APIs first - thanks for the links elsewhere.

**Comment by glowkeeper** [comment]
In lieu of any other suggestions, I'm going to take inspiration from the Open Credit Network website. Naysayers speak up now :)

**Comment by dilgreen** [comment]
Steve - I'm doing about forty things at once. This is a good suggestion, don't let time waste if you're ready to go. But let's have a call after 5 today?
D

Dil Green
[digital anthropology blog](http://www.digital-anthropology.me)
[Open Credit Network](http://opencredit.network)
@dilgreen on twitter and generally
Use this link to book a half hour slot with me!
https://calendly.com/dilgreen/30-min-video-call

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by glowkeeper** [comment]
![layout](https://user-images.githubusercontent.com/9264929/81659947-1d5aff80-9432-11ea-9407-f9ac9e06dc85.png)

**Comment by dilgreen** [comment]
Figma layout / screen flow work here: https://www.figma.com/file/KwyS2pKd8b0vUwoUJBjdge/OCN-SCREENS?node-id=0%3A1

**Comment by glowkeeper** [comment]
They look great!
